---
MODEL_DIR: ../output/model_v1
OUTPUT_JSON_PATH: ../output/inference_example.json


QUESTIONS:
  1: ['夜柔吠陀與阿闥婆吠陀均可以最為研究哪一門語言的參考？',
      '哪一本書規範了梵語的正確語法？',
      '中古印度-雅利安語方言的前身與哪一門語言都同時在古印度使用？'
  ]
  2: ['波你尼梵語與哪一門語言非常相似？',
      '印度教的最早宗教文本以什麼語言撰寫？',
      '吠陀梵語大約到何時開始演變成古典梵語？'
  ]
  3: ['儒略日的使用者中以什麼族群為多數？',
      '儒略日以什麼時間點當作起點？',
      '一般日期中的時間00:30:00在儒略日期中以多少來表示'
  ]
  4: ['2013年職業網球協會挑戰賽所試的新規則是其主辦方與哪一組織討論的？',
      '如果網球選手沒有在球回彈兩次之前用球拍擊球一次會有什麼結果？',
      '如果在網球比賽的過程中某選手故意擊球兩次會導致什麼結果？'
  ] 


TEXT:
  1: ['要探討從梨俱吠陀到波你尼時代梵語的發展，可以考察印度教其它文本，如娑摩吠陀、夜柔吠陀、阿闥婆吠陀、梵書和奧義書。在此期間，這門語言的威望、它的神聖用途及其正確發音的重要性，形成了一股強大的保守力量，防止梵語像普通語言一樣隨時間而演變。現存最古老的梵語文法是波你尼的《八篇書》，大約於公元前四世紀成形。它本質上是規範性文法，就是說它定義了正確梵語的用法，儘管它包含了描述成分，但大多是處理在波你尼時代已經廢棄了的某些吠陀形式。這裡所說的「梵語」不作脫離於其他語言的特殊語言看待，而是視作講話的高雅純正或完美方式。通過梵語文法家如波你尼的精密分析，梵語的知識在古印度是社會等級層次高和教育程度高的標誌，並主要教授給高等世襲階級的成員。梵語作為古印度的學術語言，與俗語同時共存，而俗語演化成了中古印度-雅利安語方言，並最終演化成了當代的各種印度-雅利安語言。']

  2: ['波你尼所定義的梵語是從更早的「吠陀」形式演化出來的。學者經常把吠陀梵語和古典或「波你尼」梵語區分為不同的方言。儘管它們非常類似，但在音韻、詞匯和語法幾方面，本質上有所不同，令學者難以理解吠陀。吠陀梵語是吠陀的語言，用它撰寫的，有一大批贊美詩、咒語、神學討論和宗教哲學討論，是印度教的最早宗教文本。現代語言學家認為梨俱吠陀結集的韻律讚美詩是最早的，是眾多作者的作品，經歷多個世紀的口頭傳承，終獲記錄為文字。奧義書標誌著吠陀時期的結束，它形成了吠陀文集傳統編撰的最後部分。目前的假定是：吠陀形式的梵語存活到公元前第一個千年的中期。大約在這個時期梵語開始從宗教和學習的第一語言轉變為第二語言，這標誌著古典時期的開始。']

  3: ['儒略日是在儒略週期內以連續的日數計算時間的計時法，主要是天文學家在使用。儒略日數的計算是從格林威治標準時間的中午開始，包含一個整天的時間，起點的時間回溯至儒略曆的西元前4713年1月1日中午12點，這個日期是三種多年週期的共同起點，且是歷史上最接近現代的一個起點。例如，2000年1月1日的世界協調時間12:00是儒略日2,451,545。儒略日期是以格林威治標準時中午12:00的儒略日加上那一天的瞬時時間的分數。儒略日期是儒略日添加小數部分所表示的儒略日數。例如，2013年1月1日00:30:00是儒略日期2,456,293.520833。']

  4: ['網球選手在一次正確的發球中，發出的球應該越過球網，並落在球網另一側斜對角發球區中的任意一點。如果球觸網但依然落在斜對角的發球區，則構成觸網，應該重新發球。如果球落網、沒有過網前就落地、落地前觸碰到除球網外的任何物體或沒有落在斜對角發球區，就是一次發球失誤。第一次發球失誤後發球手可以再發一次，但如果依然失誤，則讓對手得一分。職業網球協會與國際網球協會目前正在討論修改發球擦網的規則，2013年的前三個月，職業網球協會挑戰賽試行新規則，發球擦網入界將被判為發球失誤，而不是「讓」。發球成功之後，接球手回擊。球員應該在球回彈兩次之前用球拍擊球一次，使球穿越球網並落在對方球場內的任意一點，否則就失一分。球手在球落地回彈之前就擊球，依然有效。但觸碰球網、在球穿越球網前擊球、用球拍之外的任何物體擊球、故意擊球兩次等其他行為都將導致失分。在雙打比賽中，在發球與首次回擊後，搭檔中的任何一位在任意回合中都可擊球，但不得同時擊球。']


...